import type { Video, Comment, UserProfile } from "@shared/schema";
import avatar1 from "@assets/generated_images/Female_creator_profile_avatar_e8edf2bd.png";
import avatar2 from "@assets/generated_images/Male_creator_profile_avatar_b4810fe5.png";
import avatar3 from "@assets/generated_images/Female_creator_avatar_casual_1078f4ce.png";
import avatar4 from "@assets/generated_images/Male_creator_avatar_artistic_5d1cf773.png";
import avatar5 from "@assets/generated_images/Female_creator_avatar_sporty_f2872bda.png";

//todo: remove mock functionality
export const mockVideos: Video[] = [
  {
    id: "1",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    description: "Découvrez ma nouvelle création artistique 🎨✨ #art #creative",
    soundName: "Son original - creativemind",
    likes: 12500,
    comments: 234,
    shares: 89,
    isLiked: false,
  },
  {
    id: "2",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    description: "Les meilleurs tips tech de la semaine 💻 #tech #tips #viral",
    soundName: "Trending Sound Mix",
    likes: 45200,
    comments: 892,
    shares: 456,
    isLiked: false,
  },
  {
    id: "3",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    description: "Routine matinale pour bien commencer la journée ☀️ #lifestyle #morning",
    soundName: "Chill Vibes - DJ Mix",
    likes: 28900,
    comments: 567,
    shares: 234,
    isLiked: false,
  },
  {
    id: "4",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    description: "L'art de la créativité en 30 secondes 🎭 #artistique #inspiration",
    soundName: "Son original - artguru",
    likes: 67800,
    comments: 1203,
    shares: 789,
    isLiked: false,
  },
  {
    id: "5",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    description: "Entraînement express 🔥 10 minutes pour tout brûler! #fitness #workout",
    soundName: "Workout Beats 2024",
    likes: 89300,
    comments: 1456,
    shares: 923,
    isLiked: false,
  },
];

//todo: remove mock functionality
export const mockComments: Comment[] = [
  {
    id: "c1",
    videoId: "1",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Incroyable ! J'adore ton style 🔥",
    likes: 45,
    createdAt: new Date("2024-11-06T10:30:00"),
  },
  {
    id: "c2",
    videoId: "1",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Tellement inspirant ! Continue comme ça 💯",
    likes: 23,
    createdAt: new Date("2024-11-06T11:15:00"),
  },
  {
    id: "c3",
    videoId: "1",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Je veux apprendre cette technique ! Tu fais des tutos ?",
    likes: 12,
    createdAt: new Date("2024-11-06T12:00:00"),
  },
];

//todo: remove mock functionality
export const mockUserProfiles: UserProfile[] = [
  {
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    bio: "Artiste digitale 🎨 | Créatrice de contenu | Paris 🇫🇷",
    followersCount: 12500,
    followingCount: 247,
    likesCount: 156700,
    videosCount: 43,
  },
  {
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    bio: "Tech enthusiast | Gadgets & Reviews | DM pour collabs 📱",
    followersCount: 45200,
    followingCount: 189,
    likesCount: 892300,
    videosCount: 128,
  },
  {
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    bio: "Lifestyle & Wellness 🌿 | Partage de bonnes vibes | Contact: lifestyle@email.com",
    followersCount: 28900,
    followingCount: 412,
    likesCount: 445600,
    videosCount: 87,
  },
  {
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    bio: "Designer & Artist 🎭 | Inspirations quotidiennes | Cours en ligne 👇",
    followersCount: 67800,
    followingCount: 156,
    likesCount: 1234500,
    videosCount: 215,
  },
  {
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    bio: "Coach sportive 💪 | Transformations | Programme perso disponible",
    followersCount: 89300,
    followingCount: 93,
    likesCount: 2156800,
    videosCount: 342,
  },
];
