import type { Video, Comment, UserProfile } from "@shared/schema";
import avatar1 from "@assets/generated_images/Female_creator_profile_avatar_e8edf2bd.png";
import avatar2 from "@assets/generated_images/Male_creator_profile_avatar_b4810fe5.png";
import avatar3 from "@assets/generated_images/Female_creator_avatar_casual_1078f4ce.png";
import avatar4 from "@assets/generated_images/Male_creator_avatar_artistic_5d1cf773.png";
import avatar5 from "@assets/generated_images/Female_creator_avatar_sporty_f2872bda.png";

//todo: remove mock functionality
export const mockVideos: Video[] = [
  {
    id: "1",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    description: "🔴 LIVE : Session créative en direct ! Venez discuter 🎨✨ #art #creative #live",
    soundName: "LIVE - creativemind",
    likes: 12500,
    comments: 3847,
    shares: 892,
    isLiked: false,
    isLive: true,
    viewersCount: 2456,
  },
  {
    id: "2",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    description: "Les meilleurs tips tech de la semaine 💻 #tech #tips #viral",
    soundName: "Trending Sound Mix",
    likes: 145200,
    comments: 8924,
    shares: 4567,
    isLiked: false,
    isLive: false,
    viewersCount: 0,
  },
  {
    id: "3",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    description: "Routine matinale pour bien commencer la journée ☀️ #lifestyle #morning",
    soundName: "Chill Vibes - DJ Mix",
    likes: 28900,
    comments: 1567,
    shares: 234,
    isLiked: false,
    isLive: false,
    viewersCount: 0,
  },
  {
    id: "4",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    description: "🔴 EN DIRECT : Création d'une œuvre d'art ! #artistique #inspiration #live",
    soundName: "LIVE - artguru",
    likes: 167800,
    comments: 12034,
    shares: 7892,
    isLiked: false,
    isLive: true,
    viewersCount: 8734,
  },
  {
    id: "5",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    description: "Entraînement express 🔥 10 minutes pour tout brûler! #fitness #workout",
    soundName: "Workout Beats 2024",
    likes: 289300,
    comments: 15678,
    shares: 9234,
    isLiked: false,
    isLive: false,
    viewersCount: 0,
  },
  {
    id: "6",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    description: "Unboxing du dernier smartphone 📱🔥 #tech #unboxing",
    soundName: "Tech Vibes",
    likes: 78400,
    comments: 4521,
    shares: 1876,
    isLiked: false,
    isLive: false,
    viewersCount: 0,
  },
  {
    id: "7",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    description: "Timelapse de ma dernière peinture 🎨 #art #timelapse",
    soundName: "Lofi Beats",
    likes: 54200,
    comments: 2987,
    shares: 1234,
    isLiked: false,
    isLive: false,
    viewersCount: 0,
  },
  {
    id: "8",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    description: "🔴 LIVE : Entraînement en direct avec vous ! 💪 #fitness #live #workout",
    soundName: "LIVE - fitnessqueen",
    likes: 234500,
    comments: 18923,
    shares: 12456,
    isLiked: false,
    isLive: true,
    viewersCount: 15234,
  },
];

//todo: remove mock functionality
export const mockComments: Comment[] = [
  // Comments for Live video 1 (creativemind - many comments because it's live)
  {
    id: "c1",
    videoId: "1",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Incroyable ! J'adore ton style 🔥",
    likes: 456,
    createdAt: new Date("2024-11-06T10:30:00"),
  },
  {
    id: "c2",
    videoId: "1",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Tellement inspirant ! Continue comme ça 💯",
    likes: 234,
    createdAt: new Date("2024-11-06T11:15:00"),
  },
  {
    id: "c3",
    videoId: "1",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Je veux apprendre cette technique ! Tu fais des tutos ?",
    likes: 189,
    createdAt: new Date("2024-11-06T12:00:00"),
  },
  {
    id: "c4",
    videoId: "1",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "Excellent travail ! Les couleurs sont magnifiques",
    likes: 567,
    createdAt: new Date("2024-11-06T12:05:00"),
  },
  {
    id: "c5",
    videoId: "1",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Salut de Paris ! Super live 🎨",
    likes: 123,
    createdAt: new Date("2024-11-06T12:10:00"),
  },
  
  // Comments for popular video 2 (techlover - high engagement)
  {
    id: "c6",
    videoId: "2",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "Trop utile ces astuces ! Merci beaucoup",
    likes: 892,
    createdAt: new Date("2024-11-05T14:20:00"),
  },
  {
    id: "c7",
    videoId: "2",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Je ne connaissais pas cette fonction ! 😮",
    likes: 543,
    createdAt: new Date("2024-11-05T14:35:00"),
  },
  {
    id: "c8",
    videoId: "2",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "Enfin quelqu'un qui explique bien 👏",
    likes: 678,
    createdAt: new Date("2024-11-05T15:00:00"),
  },
  {
    id: "c9",
    videoId: "2",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Partagé à tous mes amis ! 📱",
    likes: 234,
    createdAt: new Date("2024-11-05T15:20:00"),
  },
  {
    id: "c10",
    videoId: "2",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "C'est exactement ce que je cherchais ❤️",
    likes: 456,
    createdAt: new Date("2024-11-05T15:45:00"),
  },
  
  // Comments for video 3 (lifestylevibe - moderate engagement)
  {
    id: "c11",
    videoId: "3",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Cette routine a l'air parfaite ! 🌅",
    likes: 156,
    createdAt: new Date("2024-11-05T08:30:00"),
  },
  {
    id: "c12",
    videoId: "3",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "Je vais essayer dès demain matin",
    likes: 89,
    createdAt: new Date("2024-11-05T09:15:00"),
  },
  {
    id: "c13",
    videoId: "3",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Super motivation ! 💪",
    likes: 234,
    createdAt: new Date("2024-11-05T10:00:00"),
  },
  
  // Comments for Live video 4 (artguru - very high engagement)
  {
    id: "c14",
    videoId: "4",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "WOW ! C'est incroyable de voir le processus en direct !",
    likes: 1234,
    createdAt: new Date("2024-11-06T13:00:00"),
  },
  {
    id: "c15",
    videoId: "4",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Combien de temps ça prend normalement ?",
    likes: 567,
    createdAt: new Date("2024-11-06T13:05:00"),
  },
  {
    id: "c16",
    videoId: "4",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Tu es un vrai artiste ! 🎨✨",
    likes: 892,
    createdAt: new Date("2024-11-06T13:10:00"),
  },
  {
    id: "c17",
    videoId: "4",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Je reste jusqu'à la fin ! 😍",
    likes: 456,
    createdAt: new Date("2024-11-06T13:15:00"),
  },
  {
    id: "c18",
    videoId: "4",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "Quelle technique tu utilises là ?",
    likes: 234,
    createdAt: new Date("2024-11-06T13:20:00"),
  },
  
  // Comments for very popular video 5 (fitnessqueen - highest engagement)
  {
    id: "c19",
    videoId: "5",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "J'ai essayé et c'est vraiment efficace ! 💪",
    likes: 1567,
    createdAt: new Date("2024-11-04T16:30:00"),
  },
  {
    id: "c20",
    videoId: "5",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Parfait pour ma pause déjeuner ! 🔥",
    likes: 2345,
    createdAt: new Date("2024-11-04T17:00:00"),
  },
  {
    id: "c21",
    videoId: "5",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Les résultats sont visibles en combien de temps ?",
    likes: 892,
    createdAt: new Date("2024-11-04T17:30:00"),
  },
  {
    id: "c22",
    videoId: "5",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "Je fais ça tous les matins maintenant ! Best workout ever",
    likes: 1234,
    createdAt: new Date("2024-11-04T18:00:00"),
  },
  {
    id: "c23",
    videoId: "5",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "Tu proposes des programmes personnalisés ?",
    likes: 456,
    createdAt: new Date("2024-11-04T18:30:00"),
  },
  
  // Comments for video 6 (techlover)
  {
    id: "c24",
    videoId: "6",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Il a l'air génial ce téléphone ! 📱",
    likes: 345,
    createdAt: new Date("2024-11-03T19:00:00"),
  },
  {
    id: "c25",
    videoId: "6",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "L'appareil photo est vraiment bon ?",
    likes: 234,
    createdAt: new Date("2024-11-03T19:30:00"),
  },
  
  // Comments for video 7 (creativemind)
  {
    id: "c26",
    videoId: "7",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "Le timelapse est magnifique ! 🎨",
    likes: 456,
    createdAt: new Date("2024-11-02T20:00:00"),
  },
  {
    id: "c27",
    videoId: "7",
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    text: "Combien de temps ça a pris ?",
    likes: 123,
    createdAt: new Date("2024-11-02T20:30:00"),
  },
  
  // Comments for Live video 8 (fitnessqueen - very high engagement)
  {
    id: "c28",
    videoId: "8",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "J'adore les lives ! On transpire ensemble 💦",
    likes: 2345,
    createdAt: new Date("2024-11-06T13:30:00"),
  },
  {
    id: "c29",
    videoId: "8",
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    text: "C'est quoi le nom de cette musique ?",
    likes: 567,
    createdAt: new Date("2024-11-06T13:35:00"),
  },
  {
    id: "c30",
    videoId: "8",
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    text: "Tu es la meilleure coach ! 🏆",
    likes: 1892,
    createdAt: new Date("2024-11-06T13:40:00"),
  },
  {
    id: "c31",
    videoId: "8",
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    text: "Je suis crevé mais je continue ! 🔥",
    likes: 892,
    createdAt: new Date("2024-11-06T13:45:00"),
  },
  {
    id: "c32",
    videoId: "8",
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    text: "À quelle heure le prochain live ?",
    likes: 456,
    createdAt: new Date("2024-11-06T13:50:00"),
  },
];

//todo: remove mock functionality
export const mockUserProfiles: UserProfile[] = [
  {
    userId: "user1",
    username: "creativemind",
    avatarUrl: avatar1,
    bio: "Artiste digitale 🎨 | Créatrice de contenu | Paris 🇫🇷",
    followersCount: 12500,
    followingCount: 247,
    likesCount: 156700,
    videosCount: 43,
  },
  {
    userId: "user2",
    username: "techlover",
    avatarUrl: avatar2,
    bio: "Tech enthusiast | Gadgets & Reviews | DM pour collabs 📱",
    followersCount: 45200,
    followingCount: 189,
    likesCount: 892300,
    videosCount: 128,
  },
  {
    userId: "user3",
    username: "lifestylevibe",
    avatarUrl: avatar3,
    bio: "Lifestyle & Wellness 🌿 | Partage de bonnes vibes | Contact: lifestyle@email.com",
    followersCount: 28900,
    followingCount: 412,
    likesCount: 445600,
    videosCount: 87,
  },
  {
    userId: "user4",
    username: "artguru",
    avatarUrl: avatar4,
    bio: "Designer & Artist 🎭 | Inspirations quotidiennes | Cours en ligne 👇",
    followersCount: 67800,
    followingCount: 156,
    likesCount: 1234500,
    videosCount: 215,
  },
  {
    userId: "user5",
    username: "fitnessqueen",
    avatarUrl: avatar5,
    bio: "Coach sportive 💪 | Transformations | Programme perso disponible",
    followersCount: 89300,
    followingCount: 93,
    likesCount: 2156800,
    videosCount: 342,
  },
];
